### ISSUE TITLE
"Hard restting vis RTS pin"

### ISSUE THREAD

**Issue by dbreunig** [SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE#11] opened 2023-10-14 17:14 UTC
Uploading any sketch via the Arduino IDE results in "Hard resetting via RTS pin". And nothing else. We see a power on print on the Serial terminal, but nothing else. Have tried with many examples and more basic code.

**Comment by rsoric** [comment] 2023-10-16 06:15
Hi @dbreunig 

that's the correct output after code upload. You might be using the wrong board definition. Try both 'Soldered ____' and 'e-Radionica ____' board definition variants for your product. They fundamentally change how the ESP interacts with the ePaper so one can't work on the other's board.

Please try the basic black and white examples first - they should always refresh the screen.

Let me know how this goes and we'll see from there.

-Rob

**Comment by dbreunig** [comment] 2023-10-16 19:04
Thanks. Switching the e-Radionica and adjusting the baud rate worked.

Now, do you know why a BMP file is rendering just as lines then a static
section?

**Comment by rsoric** [comment] 2023-10-17 07:02
You're welcome @dbreunig 

How are you loading the bmp, via the SD card, or did you use the Image converter to save it to RAM?

**Comment by BornaBiro** [comment] 2024-03-05 14:16
Since the issue is fixed and the problem with the bitmap should be asked [here](https://github.com/SolderedElectronics/Inkplate-Arduino-library) I'm closing this issue.

If you have any other problems or questions, feel free to re-open the issue.

**Closed by BornaBiro** 2024-03-05 14:16 UTC
