### ISSUE TITLE
Inkplate fails to install on Ubuntu Arm

### ISSUE THREAD

**Issue by markus-seidl** [SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE#3] opened 2023-02-12 12:16 UTC
Error message:

"Error downloading .../ESP32_Tools/3.0.0/esptool-3.3-linux.tar.gz"
which doesn't exist in the repository. My guess, it's from this entry:

```
 {
                    "name": "esptool_py",
                    "version": "4.2.1",
                    "systems": [
                        {
                            "host": "i686-mingw32",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-4.2.1-windows.zip",
                            "archiveFileName": "esptool-4.2.1-windows.zip",
                            "checksum": "SHA-256:582560067bfbd9895f4862eb5fdf87558ddee5d4d30e7575c9b8bcb0dd60fd94",
                            "size": "6368279"
                        },
                        {
                            "host": "x86_64-mingw32",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-4.2.1-windows.zip",
                            "archiveFileName": "esptool-4.2.1-windows.zip",
                            "checksum": "SHA-256:582560067bfbd9895f4862eb5fdf87558ddee5d4d30e7575c9b8bcb0dd60fd94",
                            "size": "6368279"
                        },
                        {
                            "host": "x86_64-apple-darwin",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-4.2.1-macos.tar.gz",
                            "archiveFileName": "esptool-4.2.1-macos.tar.gz",
                            "checksum": "SHA-256:a984f7ad8bdb40c42d0d368bf4bb21b69a9587aed46b7b6d7de23ca58a3f150d",
                            "size": "5816598"
                        },
                        {
                            "host": "x86_64-pc-linux-gnu",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-4.2.1-linux.tar.gz",
                            "archiveFileName": "esptool-4.2.1-linux.tar.gz",
                            "checksum": "SHA-256:5a45fb77eb6574554ec2f45230d0b350f26f9c24ab3b6c13c4031ebdf72a34ab",
                            "size": "90123"
                        },
                        {
                            "host": "i686-pc-linux-gnu",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-4.2.1-linux.tar.gz",
                            "archiveFileName": "esptool-4.2.1-linux.tar.gz",
                            "checksum": "SHA-256:5a45fb77eb6574554ec2f45230d0b350f26f9c24ab3b6c13c4031ebdf72a34ab",
                            "size": "90123"
                        },
                        {
                            "host": "arm-linux-gnueabihf",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-4.2.1-linux.tar.gz",
                            "archiveFileName": "esptool-4.2.1-linux.tar.gz",
                            "checksum": "SHA-256:5a45fb77eb6574554ec2f45230d0b350f26f9c24ab3b6c13c4031ebdf72a34ab",
                            "size": "90123"
                        },
                        {
                            "host": "aarch64-linux-gnu",
                            "url": "https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/ESP32_Tools/3.0.0/esptool-3.3-linux.tar.gz",
                            "archiveFileName": "esptool-4.2.1-linux.tar.gz",
                            "checksum": "SHA-256:5a45fb77eb6574554ec2f45230d0b350f26f9c24ab3b6c13c4031ebdf72a34ab",
                            "size": "90123"
                        }
                    ]
                },
```

which uses 3.3 for aarch64. Looking at the last entry, it looks like an error.
My system:

```
parallels@ubuntu-linux-22-04-desktop:~$ lscpu
Architecture:          aarch64
  CPU op-mode(s):      64-bit
  Byte Order:          Little Endian
```

**Comment by BornaBiro** [comment] 2023-02-20 08:07
Hello @markus-seidl.

Yes, the link for the linux-aarch64 is totally wrong (it's from the old version of the board definition, it must be some copy/paste error).
Error is fixed in the new version of the Inkplate Board Definition. Try to update Inkplate Board Definition.

**Comment by BornaBiro** [comment] 2023-05-05 07:26
@markus-seidl Hello and sorry for bothering you, but I just wanna know did our update of the board definition fix the issue or does the problem still exists.

**Comment by BornaBiro** [comment] 2023-05-11 11:53
The issue is closed due to no more activity.
If there is still a problem with the board definition, please feel free to re-open a problem.

**Closed by BornaBiro** 2023-05-11 11:53 UTC
